### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by mmrvelj** [zhouchangxun/ngx_healthcheck_module#15]
According to instructions I was not able to compile. Minor modifications where needed (CentOS 7.5).
This seems to work for me: 

git clone **https://github.com/nginx/nginx.git**
git clone https://github.com/zhouchangxun/ngx_healthcheck_module.git

cd nginx/; 
**git checkout branches/stable-1.12**
git apply **../ngx_healthcheck_module/nginx_healthcheck_for_nginx_1.12+.patch**

./auto/configure --with-stream --add-module=../ngx_healthcheck_module/
make && make install

**Comment by zhouchangxun** [comment]
@mmrvelj Thank you and you're right ! `README.md` has been updated.
