### ISSUE TITLE
check_http_send doesn't work in stream configuration

### ISSUE THREAD

**Issue by musicccman** [zhouchangxun/ngx_healthcheck_module#17]
Hi! thank you for great module! 
It seems there is an issue when working with Four-layer balancing. I try to check upstream servers in tcp balancing by http health check on custom endpoint and I cannot define endpoint by 'check_http_send' option. It always send's requests to "/" instead of "/my_custom_endpoint". The same configuration works fine when checking servers in http Seven-later balancing

**Comment by zhouchangxun** [comment]
@musicccman thank you for your feedback!
I have fixed this bug on master branch [commit link](https://github.com/zhouchangxun/ngx_healthcheck_module/commit/4640055528ce0d511c1906a31f506d9f33ad310a#diff-0b94141696138f676958b0146d0c2e54), you need pull the code and recompile it.

**Comment by musicccman** [comment]
Hi, Thank you! I also fixed that a week ago (found extra lines that override config) and tried to create a pull request but wasn't able to push my branch because of github issues :( maybe I did something wrong. But thanks for your time on this issue!

**Comment by zhouchangxun** [comment]
> Hi, Thank you! I also fixed that a week ago (found extra lines that override config) and tried to create a pull request but wasn't able to push my branch because of github issues :( maybe I did something wrong. But thanks for your time on this issue!

Haha, I am late.
You're great! :+1:
