### ISSUE TITLE
Nginx1.15是否支持？

### ISSUE THREAD

**Issue by acshmily** [zhouchangxun/ngx_healthcheck_module#18]
目前将您的这个项目交由组内运维同事进行编译测试。测试1.14可以通过、1.15下不通过。

**Comment by saga1015** [comment]
@acshmily 兄弟，1.15支持 以及1.17也支持
你编译的时候一定别忘了加--with-stream，否则编译不会通过的

**Comment by johneexu** [comment]
@acshmily 验证1.15版本可以直接执行pach 并加载module编译 
patch -p1 < /opt/nginx-1.15.7/bundle/ngx_healthcheck_module/nginx_healthcheck_for_nginx_1.14+.patch
--with-stream --add-module=bundle/ngx_healthcheck_module

**Comment by acshmily** [comment]
> @acshmily 验证1.15版本可以直接执行pach 并加载module编译
> patch -p1 < /opt/nginx-1.15.7/bundle/ngx_healthcheck_module/nginx_healthcheck_for_nginx_1.14+.patch
> --with-stream --add-module=bundle/ngx_healthcheck_module

谢谢,已经安排了.亲测可用
