### ISSUE TITLE
When tcp check successed, error log(11: Resource temporarily unavailable)

### ISSUE THREAD

**Issue by johneexu** [zhouchangxun/ngx_healthcheck_module#21]
when tcp check successed, still log exist blew error
[ngx-healthcheck][stream] when recv one byte, recv(): -1, fd: 3 (11: Resource temporarily unavailable)
when tcp check failed, error log is blew:
[ngx-healthcheck][stream] when recv one byte, recv(): -1, fd: 3 (111: Connection refused)
and in tcp error , nginx error_log level is [info] .

**Comment by zhouchangxun** [comment]
I have moved log statement to the place same with your patch above.
Now just when exception occur will print error log :)
