### ISSUE TITLE
被标记不可用的时间

### ISSUE THREAD

**Issue by TwitchChen** [zhouchangxun/ngx_healthcheck_module#22]
问一下：
1、当服务被标记为不可用，这个时间维持多久，是检测中的timeout时间吗？

2、当一个服务被标记不可用的时间到了，恰好在检测的时候又请求进来，会转发到这个服务吗？

**Comment by zhouchangxun** [comment]
@TwitchChen 
1、当服务被标记为不可用，这个时间维持多久，是检测中的timeout时间吗？
**answer**: 被标记为不可用之后还是会按照配置的interval 时间间隔定期检查，直到达到rise健康阈值就会再次被标记为可用。
2、当一个服务被标记不可用的时间到了，恰好在检测的时候又请求进来，会转发到这个服务吗？
**恰好**只是说时间接近，其实也是有先后顺序的，请求进来之后就会去查询健康后端，如果刚好在请求进来后、调用查询函数之前被标记不可用，那就不会转发到这个服务。
