### ISSUE TITLE
Mac compile ../ngx_healthcheck_module/ngx_http_upstream_check_module.c:58:9: note: did you intend to use       '#pragma pack (pop)' instead of '#pragma pack()'? #pragma pack()

### ISSUE THREAD

**Issue by yangzelin** [zhouchangxun/ngx_healthcheck_module#24]
../ngx_healthcheck_module/ngx_http_upstream_check_module.c:58:9: note: did you intend to use
      '#pragma pack (pop)' instead of '#pragma pack()'?
#pragma pack()

**Comment by zhouchangxun** [comment]
这个patch修复了在mac上的编译问题：https://github.com/zhouchangxun/ngx_healthcheck_module/commit/52efc9a5bcfc443528034191b005929db8fdb844

如有需要，请下载master最新代码进行测试并反馈是否修复。
