### ISSUE TITLE
http 健康检查在rise>1, upstream keepalive 情况下只会探测一次

### ISSUE THREAD

**Issue by wohaiaini** [zhouchangxun/ngx_healthcheck_module#28]
因为第一次检测成功后，后端是长连接时，这个时候 peer->pc.connection != NULL
第二次就会在ngx_http_upstream_check_begin_handler()中返回，此时shm->rise_count也就没有更新

下面部分是我修改的代码(patch)，周大侠看看修改是否妥当，或者怎么修改比较好呢？多谢

`
--- ngx_healthcheck_module-master/ngx_http_upstream_check_module.c      2020-04-23 10:48:26.000000000 +0800
+++ ngx_http_upstream_check_module.c    2020-04-23 10:50:05.000000000 +0800
@@ -931,6 +931,13 @@

     ngx_add_timer(event, ucscf->check_interval / 2);

++//  wohaiaini
++    if (peer->pc.connection && peer->shm->rise_count < ucscf->rise_count)
++    {
++        ngx_http_upstream_check_connect_handler(event);
++        return;
++    }
++
     /* This process is processing this peer now. */
     if ((peer->shm->owner == ngx_pid  ||
         (peer->pc.connection != NULL) ||
`

@zhouchangxun

**Comment by zhouchangxun** [comment]
@wohaiaini 
第一次检测成功后，后端是长连接时，这个时候 peer->pc.connection != NULL

> 因为第一次检测成功后，后端是长连接时，这个时候 peer->pc.connection != NULL
> 第二次就会在ngx_http_upstream_check_begin_handler()中返回，此时shm->rise_count也就没有更新
> 
> 下面部分是我修改的代码(patch)，周大侠看看修改是否妥当，或者怎么修改比较好呢？多谢
> 
> `
> --- ngx_healthcheck_module-master/ngx_http_upstream_check_module.c 2020-04-23 10:48:26.000000000 +0800
> +++ ngx_http_upstream_check_module.c 2020-04-23 10:50:05.000000000 +0800
> @@ -931,6 +931,13 @@
> 
> ```
>  ngx_add_timer(event, ucscf->check_interval / 2);
> ```
> 
> ++// wohaiaini
> ++ if (peer->pc.connection && peer->shm->rise_count < ucscf->rise_count)
> ++ {
> ++ ngx_http_upstream_check_connect_handler(event);
> ++ return;
> ++ }
> ++
> /* This process is processing this peer now. */
> if ((peer->shm->owner == ngx_pid ||
> (peer->pc.connection != NULL) ||
> `
> 
> @zhouchangxun

**Comment by zhouchangxun** [comment]
请测试后留言反馈。
如果问题已修复，我就关掉这个issue
