### ISSUE TITLE
docker环境UDP检测超时

### ISSUE THREAD

**Issue by TravelEngineers** [zhouchangxun/ngx_healthcheck_module#37]
在同一个Docker实例中，
NC检测结果：
nc -zvu 172.23.83.193 7660
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to 172.23.83.193:7660.
Ncat: UDP packet sent successfully
Ncat: 1 bytes sent, 0 bytes received in 2.01 seconds.

插件检测结果：
 [ngx_healthcheck:stream][timer]udp check time out with peer: 172.23.83.193:7660, we assum it's up :)

**Comment by zhouchangxun** [comment]
> 在同一个Docker实例中，
> NC检测结果：
> nc -zvu 172.23.83.193 7660
> Ncat: Version 7.50 ( https://nmap.org/ncat )
> Ncat: Connected to 172.23.83.193:7660.
> Ncat: UDP packet sent successfully
> Ncat: 1 bytes sent, 0 bytes received in 2.01 seconds.
> 
> 插件检测结果：
> [ngx_healthcheck:stream][timer]udp check time out with peer: 172.23.83.193:7660, we assum it's up :)

1 bytes sent, **0** bytes received in 2.01 seconds.
你的udp server会回包吗？我看你用nc测试，也没回包。
这个nginx插件，对于udp检测，如果没有收到icmp端口不可达，会认定为UP。

**Comment by TravelEngineers** [comment]
他貌似收不到发送的包，现在已经不用了，应该是代理之后地址变更导致有问题的。
