### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by markus9203902** [zhouchangxun/ngx_healthcheck_module#6]
Hi! I've encounter a build issue while building the  v1.0 branch.

`make[1]: *** Waiting for unfinished jobs....
/root/nginx_build/ngx_healthcheck_module/ngx_stream_upstream_check_module.c: In function ‘ngx_stream_upstream_check_init_shm_zone’:
/root/nginx_build/ngx_healthcheck_module/ngx_stream_upstream_check_module.c:2158:31: error: ‘ngx_upstream_check_peer_shm_t’ undeclared (first use in this function)
            (number ) * sizeof(ngx_upstream_check_peer_shm_t);//last item not use :)
                               ^
/root/nginx_build/ngx_healthcheck_module/ngx_stream_upstream_check_module.c:2158:31: note: each undeclared identifier is reported only once for each function it appears in
objs/Makefile:1804: recipe for target 'objs/addon/ngx_healthcheck_module/ngx_stream_upstream_check_module.o' failed`

I found out that in files ngx_stream_upstream_check_module.c and ngx_http_upstream_check_module.c there is a part of code which cause a build failure because of undefined **ngx_upstream_check_peer_shm_t** 

https://github.com/zhouchangxun/ngx_healthcheck_module/blob/v1.0/ngx_stream_upstream_check_module.c#L2158

`    size = sizeof(*peers_shm) +
(number ) * sizeof(ngx_upstream_check_peer_shm_t);//last item not use :)`

Should I erase all these two lines, or use a source from the master branch? 
Thanks.

**Comment by zhouchangxun** [comment]
@markus9203902 I have solved this problem and thank you for your feedback.

**Comment by markus9203902** [comment]
@zhouchangxun fixed, TY. I'm using master now and built from it - no problems encountered for now.
