### ISSUE TITLE
/status?format=json&status=down 获取的返回不是标准的json

### ISSUE THREAD

**Issue by cppddz** [zhouchangxun/ngx_healthcheck_module#9]
使用/status?format=json&status=down 查询状态。
返回的格式是这样的， {"http": [ {}, {}， ]} 。]左边多了个逗号。

`{"servers": {
  "total": 6,
  "generation": 3,
  "http": [
    {"index": 0, "upstream": "http-cluster", "name": "127.0.0.1:8080", "status": "up", "rise": 119, "fall": 0, "type": "http", "port": 0},
    {"index": 1, "upstream": "http-cluster", "name": "127.0.0.2:81", "status": "down", "rise": 0, "fall": 120, "type": "http", "port": 0}，
  ],
  "stream": [
    {"index": 0, "upstream": "tcp-cluster", "name": "127.0.0.1:22", "status": "up", "rise": 22, "fall": 0, "type": "tcp", "port": 0},
    {"index": 1, "upstream": "tcp-cluster", "name": "192.168.0.2:22", "status": "down", "rise": 0, "fall": 7, "type": "tcp", "port": 0},
    {"index": 2, "upstream": "udp-cluster", "name": "127.0.0.1:53", "status": "down", "rise": 0, "fall": 120, "type": "udp", "port": 0},
    {"index": 3, "upstream": "udp-cluster", "name": "8.8.8.8:53", "status": "up", "rise": 3, "fall": 0, "type": "udp", "port": 0}，
  ]
}}`

**Comment by zhouchangxun** [comment]
感谢反馈，已在新的提交中解决。请拉取最新master代码验证。
